name: walletconnect_secure_storage
description: Securely store WalletConnect sessions in your Flutter applications using walletconnect_dart.
version: 1.0.0
homepage: https://walletconnect.org/
repository: https://github.com/RootSoft/walletconnect-secure-storage
issue_tracker: https://github.com/RootSoft/walletconnect-secure-storage/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # WalletConnect
  walletconnect_dart: ^0.0.5

  # Flutter Secure Storage
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

